from typing import Protocol

from e2epool.inventory import RunnerConfig


class BackendProtocol(Protocol):
    def create_checkpoint(self, runner: RunnerConfig, name: str) -> None: ...
    def reset(self, runner: RunnerConfig, name: str) -> None: ...
    def cleanup(self, runner: RunnerConfig, name: str) -> None: ...
    def check_ready(self, runner: RunnerConfig) -> bool: ...
