"""initial_schema

Revision ID: 1547a28ef314
Revises: 
Create Date: 2026-02-13 13:44:30.495965

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1547a28ef314'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('runner_id', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('finalize_status', sa.String(length=50), nullable=True),
    sa.Column('finalize_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("finalize_status IS NULL OR finalize_status IN ('success', 'failure', 'canceled')", name='ck_checkpoint_finalize_status'),
    sa.CheckConstraint("state IN ('created', 'finalize_queued', 'reset', 'deleted', 'gc_reset')", name='ck_checkpoint_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_checkpoints_runner_id'), 'checkpoints', ['runner_id'], unique=False)
    op.create_index('ix_one_active_checkpoint_per_runner', 'checkpoints', ['runner_id'], unique=True, postgresql_where=sa.text("state IN ('created', 'finalize_queued')"))
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_checkpoint_id'), 'operation_logs', ['checkpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_logs_checkpoint_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('ix_one_active_checkpoint_per_runner', table_name='checkpoints', postgresql_where=sa.text("state IN ('created', 'finalize_queued')"))
    op.drop_index(op.f('ix_checkpoints_runner_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
